export const ADD_TO_CART='ADD_TO_CART';
export const DELETE_FROM_CART='DELETE_FROM_CART';
// export const ADD_TO_WISHLIST='ADD_TO_WISHLIST';
// export const DELETE_FROM_WISHLIST='DELETE_FROM_WISHLIST';
export const DELETE_PL_FROM_CART='DELETE_PL_FROM_CART';
export const ADD_PL_TO_CART="ADD_PL_TO_CART";


export const FETCH_CART_REQUEST="FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS="FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE="FETCH_CART_FAILURE";