export const ADD_TO_WISHLIST='ADD_TO_WISHLIST';
export const DELETE_FROM_WISHLIST='DELETE_FROM_WISHLIST'

export const FETCH_WISHLIST_FAILURE='FETCH_WISHLIST_FAILURE'
export const FETCH_WISHLIST_SUCCESS='FETCH_WISHLIST_SUCCESS'
export const FETCH_WISHLIST_REQUEST='FETCH_WISHLIST_REQUEST'
